version: "3"
networks:
  application:
    driver: bridge
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: mybackend
    ports:
      - 8000:8000
    environment:
      - DB_HOST=pgdb
    networks:
      - application
    volumes:
      - .:/app